// <auto-generated />
using Flix.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Flix.API.Migrations
{
    [DbContext(typeof(FlixDataContext))]
    [Migration("20211129005552_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Flix.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmeId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmeId = 1,
                            Nome = "Ação"
                        },
                        new
                        {
                            Id = 2,
                            FilmeId = 2,
                            Nome = "Biografia"
                        },
                        new
                        {
                            Id = 3,
                            FilmeId = 3,
                            Nome = "Horror"
                        },
                        new
                        {
                            Id = 4,
                            FilmeId = 4,
                            Nome = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            FilmeId = 5,
                            Nome = "Comédia"
                        });
                });

            modelBuilder.Entity("Flix.API.Models.Espectador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Espectadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Dennis",
                            Sobrenome = "Ritchie",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Roberto",
                            Sobrenome = "Ierusalimschy",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Bjarn",
                            Sobrenome = "Straustrup",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Ada",
                            Sobrenome = "Lovelace",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Konrad",
                            Sobrenome = "Zuze",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Guido",
                            Sobrenome = "van Rossum",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Anders",
                            Sobrenome = "Hejlsberg",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("Flix.API.Models.EspectadorCategoria", b =>
                {
                    b.Property<int>("EspectadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EspectadorId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("EspectadorCategorias");

                    b.HasData(
                        new
                        {
                            EspectadorId = 1,
                            CategoriaId = 2
                        },
                        new
                        {
                            EspectadorId = 1,
                            CategoriaId = 4
                        },
                        new
                        {
                            EspectadorId = 1,
                            CategoriaId = 5
                        },
                        new
                        {
                            EspectadorId = 2,
                            CategoriaId = 1
                        },
                        new
                        {
                            EspectadorId = 2,
                            CategoriaId = 2
                        },
                        new
                        {
                            EspectadorId = 2,
                            CategoriaId = 5
                        },
                        new
                        {
                            EspectadorId = 3,
                            CategoriaId = 1
                        },
                        new
                        {
                            EspectadorId = 3,
                            CategoriaId = 2
                        },
                        new
                        {
                            EspectadorId = 3,
                            CategoriaId = 3
                        },
                        new
                        {
                            EspectadorId = 4,
                            CategoriaId = 1
                        },
                        new
                        {
                            EspectadorId = 4,
                            CategoriaId = 4
                        },
                        new
                        {
                            EspectadorId = 4,
                            CategoriaId = 5
                        },
                        new
                        {
                            EspectadorId = 5,
                            CategoriaId = 4
                        },
                        new
                        {
                            EspectadorId = 5,
                            CategoriaId = 5
                        },
                        new
                        {
                            EspectadorId = 6,
                            CategoriaId = 1
                        },
                        new
                        {
                            EspectadorId = 6,
                            CategoriaId = 2
                        },
                        new
                        {
                            EspectadorId = 6,
                            CategoriaId = 3
                        },
                        new
                        {
                            EspectadorId = 6,
                            CategoriaId = 4
                        },
                        new
                        {
                            EspectadorId = 7,
                            CategoriaId = 1
                        },
                        new
                        {
                            EspectadorId = 7,
                            CategoriaId = 2
                        },
                        new
                        {
                            EspectadorId = 7,
                            CategoriaId = 3
                        },
                        new
                        {
                            EspectadorId = 7,
                            CategoriaId = 4
                        },
                        new
                        {
                            EspectadorId = 7,
                            CategoriaId = 5
                        });
                });

            modelBuilder.Entity("Flix.API.Models.EspectadorFilme", b =>
                {
                    b.Property<int>("EspectadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EspectadorId", "FilmeId");

                    b.ToTable("EspectadoresFilmes");

                    b.HasData(
                        new
                        {
                            EspectadorId = 3,
                            FilmeId = 3
                        },
                        new
                        {
                            EspectadorId = 6,
                            FilmeId = 3
                        },
                        new
                        {
                            EspectadorId = 1,
                            FilmeId = 1
                        },
                        new
                        {
                            EspectadorId = 1,
                            FilmeId = 3
                        },
                        new
                        {
                            EspectadorId = 1,
                            FilmeId = 5
                        },
                        new
                        {
                            EspectadorId = 2,
                            FilmeId = 1
                        },
                        new
                        {
                            EspectadorId = 2,
                            FilmeId = 2
                        },
                        new
                        {
                            EspectadorId = 2,
                            FilmeId = 5
                        },
                        new
                        {
                            EspectadorId = 3,
                            FilmeId = 1
                        },
                        new
                        {
                            EspectadorId = 3,
                            FilmeId = 2
                        },
                        new
                        {
                            EspectadorId = 4,
                            FilmeId = 1
                        },
                        new
                        {
                            EspectadorId = 4,
                            FilmeId = 4
                        },
                        new
                        {
                            EspectadorId = 5,
                            FilmeId = 4
                        },
                        new
                        {
                            EspectadorId = 5,
                            FilmeId = 5
                        },
                        new
                        {
                            EspectadorId = 6,
                            FilmeId = 1
                        },
                        new
                        {
                            EspectadorId = 6,
                            FilmeId = 2
                        },
                        new
                        {
                            EspectadorId = 6,
                            FilmeId = 4
                        },
                        new
                        {
                            EspectadorId = 7,
                            FilmeId = 1
                        },
                        new
                        {
                            EspectadorId = 7,
                            FilmeId = 2
                        },
                        new
                        {
                            EspectadorId = 7,
                            FilmeId = 3
                        },
                        new
                        {
                            EspectadorId = 7,
                            FilmeId = 4
                        },
                        new
                        {
                            EspectadorId = 7,
                            FilmeId = 5
                        });
                });

            modelBuilder.Entity("Flix.API.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Selva"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Imperador"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Susto"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Vida"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Felicidade"
                        });
                });

            modelBuilder.Entity("Flix.API.Models.Categoria", b =>
                {
                    b.HasOne("Flix.API.Models.Filme", "Filme")
                        .WithMany("Categorias")
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flix.API.Models.EspectadorCategoria", b =>
                {
                    b.HasOne("Flix.API.Models.Categoria", "Categoria")
                        .WithMany("EspectadorCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flix.API.Models.Espectador", "Espectador")
                        .WithMany("EspectadorCategorias")
                        .HasForeignKey("EspectadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flix.API.Models.EspectadorFilme", b =>
                {
                    b.HasOne("Flix.API.Models.Espectador", null)
                        .WithMany("EspectadoresFilmes")
                        .HasForeignKey("EspectadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
